# Generated by Django 4.2.4 on 2023-09-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allDay',
            field=models.CharField(default='false', max_length=5),
            preserve_default=False,
        ),
    ]
