# Generated by Django 4.2.4 on 2023-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_allday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
