# Generated by Django 4.2.4 on 2023-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allDay',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
